name: log_manager
description: "A log manager plugin"
version: 0.2.1
homepage: http://didur.dev.br

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  intl: ^0.19.0
  json_annotation: ^4.9.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  plugin:
    platforms:
      android:
        package: br.dev.didur.app.log_manager
        pluginClass: LogManagerPlugin
      ios:
        pluginClass: LogManagerPlugin
